//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Datos_Pelicula()
        {
            this.Reparto_Pelicula = new HashSet<Reparto_Pelicula>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Pelicula { get; set; }
        public string Descripcion { get; set; }
        public string Trailer { get; set; }
        public string Opinion_Usuario { get; set; }
        public string Puntuacion_Usuario { get; set; }
    
        public virtual Peliculas Peliculas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparto_Pelicula> Reparto_Pelicula { get; set; }
    }
}
